name: dart_mcp
description: A Dart implementation of the Model Context Protocol (MCP)
version: 1.0.0
repository: https://github.com/lollipopkit/mcp_dart

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^3.0.4
  json_serializable: ^6.7.1
  lints: ^5.1.1
  test: ^1.24.0
