name: dart_mcp
description: A Dart implementation of the Model Context Protocol (MCP)
version: 1.0.0
repository: https://github.com/cristhro/dart_mcp

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6
  dart_code_metrics_presets: ^1.8.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.0
